### PR TITLE
Decode entities in the URL

### PR DESCRIPTION
**Pull request by rmccue**
Currently, HTML entities in the URL are not decoded, leading to ampersands not being decoded in the URL.

This can be reproduced by accessing the current link on http://www.reddit.com/r/rmccuetest via both the web and via iReddit. In iReddit, the URL is shown to have `&amp;` instead of `&`.

This commit fixes it. (And only includes the one commit, unlike the other request)

### CODE REVIEW

**Comment by rmccue** [comment]
Whoops, didn't notice rbruels merged my fix in! Closing, since it's fixed now.

**Comment by rbruels** [comment]
Hi rmccue,

Sorry, I meant to write a comment earlier. Thanks for the URL escaping fix, not sure how that went on for so long!

The HTML/CSS/JS consolidation caused threads in "saved" posts (and possibly others) to bork for some reason—judging from the behavior (thread not loading, spurious bits of the HTML showing up) my _guess_ is that there was a syntax error thrown in the JS, but I didn't have time to debug. What was the intent of the changes?

Also, we didn't pull your swipe changes forward since:
a.) they were really just stubs for future functionality
b.) the swipe gesture recognizers would have prevented us from deploying the app on anything earlier than iOS 4 (which isn't really ubiquitous quite yet)

The point of the most recent pull was just to get the app onto stock Three20 and a few other important bug fixes/enhancements, enough to get it stable again for the App Store—now the community can get back to feature development and other bug fixes. In particular I'm planning a complete re-architecture of the comment threads since they are so slow and not-very-iPhone-y.

Maybe once I get a few more cycles we can conspire together on plans for the next update.

**Comment by rmccue** [comment]
The idea of the HTML/CSS/JS changes (at least, the ones you were going to pull in) is to separate them into separate files, so that we could hopefully move the CSS/JS to reddit.com. This would allow the CSS/JS to be updated separately. Ideally, this would be updated when the app is opened for the first time, then cached for the rest of the uses.

If you're going to re-architecture the comment threads (native Cocoa widgets instead of a HTML view?), I'm all for that though. I'm not entirely sure why it used a HTML file in the first place.

Regarding the swipe changes, they should have only been on my swiping branch, and I accidentally committed them to the wrong branch previously. I removed those changes, but I guess I forgot to push. :)
The actual changes with the swiping are on the [swiper branch](https://github.com/rmccue/iReddit/tree/swiper).

Thanks for your changes. I'm hoping a new version will go up on the App Store soon. I'm somewhat sick of the app crashing, but I was unable to reproduce this myself (I don't have a dev license, so I've been using the simulator).

**Comment by rbruels** [comment]
Yes, my plan was to go with Cocoa widgets and native parsing—I agree, not sure why it was a web view to begin with. 

ketralnis has posted the new version to the App Store, so it's in Apple's hands now. The multitasking support alone makes it worth it, but that annoying lock-up-the-whole-app problem is gone too. Never was able to trace the _exact_ cause, except that it was definitely coming from the old Three20 build. I've been doing this iOS thing going on 3 years now, and I've never been able to lock up an app like that without the phone killing the app in the process. Pretty notable, haha.

All good changes! I hope everyone enjoys the fixes.

**Comment by rmccue** [comment]
Well, that's awesome then. I've been learning Obj-C as I go, so I was unable to trace it too. Leaks in Instruments showed a very small leak in some of the Three20 code, but it was pretty small.

**Pull request closed without merging**
